# Generated by Django 4.2.1 on 2023-06-04 15:35

import custom.storage_backends
import custom.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('custom', '0002_alter_lesson_video'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lesson',
            name='video',
            field=models.FileField(blank=True, null=True, storage=custom.storage_backends.LocalMediaStorage(), upload_to='course/videos', validators=[custom.validators.FileSizeValidator(max_mb=10), django.core.validators.FileExtensionValidator(allowed_extensions=['mp4', 'webm', 'ogg'])]),
        ),
    ]
